spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      database: postgresql
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082